version: '3'

services:
  iam:
    container_name: iam
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    volumes:
      - .:/root/src
    logging:
      options:
        max-size: "500k"
    ports:
      - "50001:3001"
