version: '3'

services:
  i-am-d:
    container_name: i-am-d
    build:
      context: .
      dockerfile: Dockerfile.build
    environment:
      - PORT=3001
    volumes:
      - .:/root/src
    logging:
      options:
        max-size: "500k"
    ports:
      - "50001:3001"
